# reg.yaml

TrainConfig:
  start_new_model: True
  max_save_num: 2                 # numbers that checkpoint files saved; default 2
  gpu: "2"
  data_path: "datasets/json/35_128_OASIS.json"
  epoch: 1000
  batchsize: 1
  checkpoint: ""
  val_interval: 10


TestConfig:
  checkpoint: ""
#  checkpoint: ""
  data_path: "datasets/json/35_128_OASIS.json"
  save_image: True
  gpu: "0"

ModelConfig:
  type: "UNet"



OptimConfig:
  load_checkpoint: False     # whether load a checkpoint in training, using the path defined in Trainconfig
  optimizer:
    type: "Adam"
    params:
      lr: 0.0001
  lr_scheduler:
    type: "StepLR"
    params:
      step_size: 100
      gamma: 0.7
      warmup: True
      warmup_steps: 100


