# reg.yaml

TrainConfig:
  start_new_model: True
  max_save_num: 2                 # numbers that checkpoint files saved; default 2
  gpu: ""
  data_path: "datasets/json/35_128_OASIS_115.json"
  epoch: 50
  batchsize: 1
  checkpoint: ""
  val_interval: 1


#  writer_board_interval: 10

TestConfig:
  checkpoint: ""
#  checkpoint: ""
  data_path: "datasets/json/35_128_OASIS_115.json"
  save_image: True
  gpu: "0"

ModelConfig:
  type: "UNet"



OptimConfig:
  load_checkpoint: False     # whether load a checkpoint in training, using the path defined in Trainconfig
  optimizer:
    type: "Adam"
    params:
      lr: 0.001
  lr_scheduler:
    type: "StepLR"
    params:
      step_size: 700
      gamma: 0.8
      warmup: True
      warmup_steps: 100


