# reg.yaml

TrainConfig:
  start_new_model: True
  max_save_num: 2                 # numbers that checkpoint files saved; default 2
  gpu: "0"
  data_path: "datasets/json/LPBA40_test.json"
  epoch: 50
  batchsize: 8
  checkpoint: ""
  val_interval: 1
  seg: "seg_28"


#  writer_board_interval: 10

TestConfig:
  checkpoint: ""
  data_path: "datasets/json/LPBA40_test.json"
  save_image: True
  gpu: "0"

ModelConfig:
  type: "vxm_diff"



OptimConfig:
  load_checkpoint: False     # whether load a checkpoint in training, using the path defined in Trainconfig
  optimizer:
    type: "Adam"
    params:
      lr: 0.0004
  lr_scheduler:
    type: "StepLR"
    params:
      step_size: 1500
      gamma: 0.5
      warmup: False
      warmup_steps: 100

LossConfig:

  similarity_loss:
    use: True
    type: 'NCCLoss'
    weight: 1

  segmentation_loss:
    use: True
    type: 'DiceLoss2'
    weight: 1

  gradient_loss:
    use: True
    type: 'GradientLoss'
    weight: 1

  bending_energy_loss:
    use: False
    type: 'BendingEnergyLoss'
    weight: 1



