# reg_semi_supervised.yaml

TrainConfig:
  start_new_model: True
  max_save_num: 2                 # numbers that checkpoint files saved; default 2
  gpu: "0"
  data_path: "datasets/json/LPBA40.json"
  epoch: 500
  batchsize: 1
  checkpoint: ""
  val_interval: 2
  seg: "seg_28"


TestConfig:
  checkpoint: ""
  data_path: "datasets/json/LPBA40.json"
  save_image: False
  gpu: "0"

ModelConfig:
  type: "vxm_diff"



OptimConfig:
  load_checkpoint: False     # whether load a checkpoint in training, using the path defined in Trainconfig
  optimizer:
    type: "Adam"
    params:
      lr: 0.0001
  lr_scheduler:
    type: "StepLR"
    params:
      step_size: 50
      gamma: 0.8
      warmup: True
      warmup_steps: 100

LossConfig:

  similarity_loss:
    use: True
    type: 'NCCLoss'
    weight: 1

  segmentation_loss:
    use: True
    type: 'DiceLoss2'
    weight: 1

  gradient_loss:
    use: True
    type: 'GradientLoss'
    weight: 1

  bending_energy_loss:
    use: False
    type: 'BendingEnergyLoss'
    weight: 1