# reg.yaml

TrainConfig:
  start_new_model: True
  max_save_num: 2                 # numbers that checkpoint files saved; default 2
  gpu: "0"
  data_path: "datasets/json/5_192_Mindboggle101.json"
  epoch: 1000
  use_mean_teacher: True
  consistency: 0.1
  consistency_loss_type: 1
  labeld_bs: 2
  batchsize: 4  
  checkpoint: ""
  val_interval: 1
  seg: "seg_59"


#  writer_board_interval: 10

TestConfig:
  checkpoint: ""
  data_path: "datasets/json/5_192_Mindboggle101.json"
  save_image: False
  gpu: "0"

ModelConfig:
  type: "vxm_diff"
  mask_type: ""



OptimConfig:
  load_checkpoint: False     # whether load a checkpoint in training, using the path defined in Trainconfig
  optimizer:
    type: "Adam"
    params:
      lr: 0.0005
  lr_scheduler:
    type: "StepLR"
    params:
      step_size: 50
      gamma: 0.5
      warmup: True
      warmup_steps: 100

LossConfig:

  similarity_loss:
    use: True
    type: 'NCCLoss'
    weight: 1

  segmentation_loss:
    use: True
    type: 'DiceLoss2'
    weight: 1

  gradient_loss:
    use: True
    type: 'GradientLoss'
    weight: 1

  bending_energy_loss:
    use: False
    type: 'BendingEnergyLoss'
    weight: 1



