# seg.yaml

TrainConfig:
  start_new_model: True
  max_save_num: 2                 # numbers that checkpoint files saved; default 2
  gpu: "0"
  data_path: "datasets/json/LPBA40.json"
  epoch: 50
  batchsize: 1
  checkpoint: ""
  val_interval: 5
  seg: "seg_28"

TestConfig:
  data_path: "datasets/json/LPBA40.json"
  checkpoint: ""
  save_image: False
  gpu: "0"

ModelConfig:
  type: "UNet"



OptimConfig:
  load_checkpoint: False     # whether load a checkpoint in training, using the path defined in Trainconfig
  optimizer:
    type: "Adam"
    params:
      lr: 0.001
  lr_scheduler:
    type: "StepLR"
    params:
      step_size: 400
      gamma: 0.8
      warmup: False
      warmup_steps: 100