TrainConfig:
  start_new_model: True
  max_save_num: 2                 # numbers that checkpoint files saved; default 2
  gpu: "0"
  data_path: "datasets/json/LPBA40.json"
  epoch: 100
  batchsize: 2
  checkpoint: ""
  val_interval: 5
  semi_supervised: False

TestConfig:
  data_path: "datasets/json/LPBA40.json"
  checkpoint: "output/seg/debug/debug4/checkpoint/last_epoch_0100.pth"
  save_image: True
  gpu: "0"

ModelConfig:
  type: "UNet"



OptimConfig:
  load_checkpoint: False     # whether load a checkpoint in training, using the path defined in Trainconfig
  optimizer:
    type: "Adam"
    params:
      lr: 0.0004
  lr_scheduler:
    type: "StepLR"
    params:
      step_size: 1500
      gamma: 0.5
      warmup: True
      warmup_steps: 100