# seg_reg.yaml

TrainConfig:
  start_new_model: True
  max_save_num: 2                 # numbers that checkpoint files saved; default 2
  data_path: "datasets/json/LPBA40_test.json"
  epoch: 50
  gpu: "0"
  M: -1
  batchsize: 2
  Seg:
    gpu: "0"
    seg_step_per_epoch: 5
    checkpoint: ""
    val_interval: 5
  Reg:
    gpu: "0"
    reg_step_per_epoch: 20
    checkpoint: ""
    val_interval: 5

TestConfig:
  gpu: "0"
  data_path: "datasets/json/LPBA40_test.json"
  save_image: True
  Seg:
    checkpoint: ""
  Reg:
    checkpoint: ""



ModelConfig:
  Seg:
    type: "UNet"
  Reg:
    type: "VoxelMorpher"


OptimConfig:
  Seg:
    load_checkpoint: False     # whether load a checkpoint in training, using the path defined in Trainconfig
    optimizer:
      type: "Adam"
      params:
        lr: 0.0004
    lr_scheduler:
      type: "StepLR"
      params:
        step_size: 1500
        gamma: 0.5
        warmup: True
        warmup_steps: 100
  Reg:
    load_checkpoint: False     # whether load a checkpoint in training, using the path defined in Trainconfig
    optimizer:
      type: "Adam"
      params:
        lr: 0.0004
    lr_scheduler:
      type: "StepLR"
      params:
        step_size: 1500
        gamma: 0.5
        warmup: True
        warmup_steps: 100


LossConfig:
  Reg:
    similarity_loss:
      use: True
      type: 'NCCLoss'
      weight: 1

    segmentation_loss:
      use: True
      type: 'MonAIDiceLoss'
      params:
        include_background: True
        to_onehot_y: False
        softmax: False
        reduction: 'mean'
      weight: 1

    gradient_loss:
      use: True
      type: 'GradientLoss'
      weight: 1

    bending_energy_loss:
      use: False
      type: 'BendingEnergyLoss'
      weight: 1

  Seg:
    supervised_loss:
      type: 'DiceLoss'
      weight: 1

    anatomy_loss:
      type: 'DiceLoss'
      weight: 1




